/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pertemuankeduabelas;
import java.util.Map;
import java.util.HashMap;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.io.BufferedReader;
import java.io.FileWriter;
import java.io.InputStreamReader;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileSystemView;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;
import javax.persistence.*;
import pertemuanketigabelas.UserNow;

/**
 *
 * @author VIVOBOOK 14
 */
public class MenuUtama extends javax.swing.JFrame {

    /**
     * Creates new form MenuUtama
     */
    public MenuUtama() {
        initComponents();
        showTablePenerbit();
        showTableBuku();
        DtPenerbit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                int row = DtPenerbit.getSelectedRow();

                int idm = Integer.parseInt(DtPenerbit.getValueAt(row, 0).toString());
                String nmp = DtPenerbit.getValueAt(row, 1).toString();
                String Alamat = DtPenerbit.getValueAt(row, 2).toString();

            }
        });
        DtBuku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                int row = DtBuku.getSelectedRow();

                int idb = Integer.parseInt(DtBuku.getValueAt(row, 0).toString());
                String jb = DtBuku.getValueAt(row, 1).toString();
                String tt = DtBuku.getValueAt(row, 2).toString();
                int idp = Integer.parseInt(DtBuku.getValueAt(row, 3).toString());

            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private DefaultTableModel model;
    Connection conn;
    Statement stmt;
    PreparedStatement pstmt = null;

    String driver = "org.postgresql.Driver";
    String koneksi = "jdbc:postgresql://localhost:5432/Arcana_Library";
    String user = "postgres";
    String password = "kapuas02";
    InputStreamReader inputStreamReader = new InputStreamReader(System.in);
    BufferedReader input = new BufferedReader(inputStreamReader);

    public void showTablePenerbit() {
        EntityManager em = Persistence.createEntityManagerFactory("PertemuanKeduabelasPU").createEntityManager();

        Query q = em.createNamedQuery("Penerbit.findAll");
        List<Penerbit> hasil = q.getResultList();

        model = new DefaultTableModel(new String[]{"Id Penerbit", "Nama Penerbit", "Alamat"}, 0);
        for (Penerbit data : hasil) {
            Object[] baris = new Object[3];
            baris[0] = data.getIdPenerbit();
            baris[1] = data.getNamaPenerbit();
            baris[2] = data.getAlamat();
            model.addRow(baris);
        }
        DtPenerbit.setModel(model);
    }

    public void showTableBuku() {
        EntityManager em = Persistence.createEntityManagerFactory("PertemuanKeduabelasPU").createEntityManager();
        Query q = em.createNamedQuery("Buku.findAll");
        List<Buku> hasil = q.getResultList();

        model = new DefaultTableModel(new String[]{"Id Buku", "Judul Buku", "Tahun Terbit", "Id Penerbit"}, 0);

        for (Buku data : hasil) {
            Object[] baris = new Object[4];
            baris[0] = data.getIdBuku();
            baris[1] = data.getJudul();
            baris[2] = data.getTahunTerbit();
            baris[3] = data.getIdPenerbit() != null ? data.getIdPenerbit().getIdPenerbit() : "-";
            model.addRow(baris);
        }

        DtBuku.setModel(model);
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        DtBuku = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        BtnInsert = new javax.swing.JButton();
        BttnDelete = new javax.swing.JButton();
        BttnUpdate = new javax.swing.JButton();
        BttnUpload = new javax.swing.JButton();
        BttnCetak = new javax.swing.JButton();
        Btnreset = new javax.swing.JButton();
        Btndownload = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        DtPenerbit = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        BtnInsrt = new javax.swing.JButton();
        BtnDeleteP = new javax.swing.JButton();
        BtnUpdate = new javax.swing.JButton();
        BtnUpload = new javax.swing.JButton();
        BtnCetak = new javax.swing.JButton();
        BtnRst = new javax.swing.JButton();
        btndwnld = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(182, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("ARCANA LIBRARY");

        jPanel3.setBackground(new java.awt.Color(0, 255, 255));

        DtBuku.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id Buku", "Judul Buku", "Tahun Terbit", "Id Penerbit"
            }
        ));
        jScrollPane1.setViewportView(DtBuku);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Data Buku");

        BtnInsert.setText("Insert");
        BtnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnInsertActionPerformed(evt);
            }
        });

        BttnDelete.setText("Delete");
        BttnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BttnDeleteActionPerformed(evt);
            }
        });

        BttnUpdate.setText("Update");
        BttnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BttnUpdateActionPerformed(evt);
            }
        });

        BttnUpload.setText("Upload");
        BttnUpload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BttnUploadActionPerformed(evt);
            }
        });

        BttnCetak.setText("Cetak");
        BttnCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BttnCetakActionPerformed(evt);
            }
        });

        Btnreset.setText("Reset");
        Btnreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnresetActionPerformed(evt);
            }
        });

        Btndownload.setText("Download");
        Btndownload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtndownloadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(222, 222, 222)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BttnCetak))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 497, Short.MAX_VALUE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(BtnInsert)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BttnDelete)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BttnUpdate)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BttnUpload)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Btnreset)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Btndownload)))))
                .addGap(26, 26, 26))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(BttnCetak)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnInsert)
                    .addComponent(BttnDelete)
                    .addComponent(BttnUpdate)
                    .addComponent(BttnUpload)
                    .addComponent(Btnreset)
                    .addComponent(Btndownload))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Buku", jPanel3);

        jPanel2.setBackground(new java.awt.Color(0, 255, 255));
        jPanel2.setForeground(new java.awt.Color(0, 255, 255));

        DtPenerbit.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Id Penerbit", "Nama Penerbit", "Alamat"
            }
        ));
        jScrollPane3.setViewportView(DtPenerbit);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Data Penerbit");

        BtnInsrt.setText("Insert");
        BtnInsrt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnInsrtActionPerformed(evt);
            }
        });

        BtnDeleteP.setText("Delete");
        BtnDeleteP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDeletePActionPerformed(evt);
            }
        });

        BtnUpdate.setText("Update");
        BtnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnUpdateActionPerformed(evt);
            }
        });

        BtnUpload.setText("Upload");
        BtnUpload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnUploadActionPerformed(evt);
            }
        });

        BtnCetak.setText("Cetak");
        BtnCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCetakActionPerformed(evt);
            }
        });

        BtnRst.setText("Reset");
        BtnRst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRstActionPerformed(evt);
            }
        });

        btndwnld.setText("Download");
        btndwnld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndwnldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(221, 221, 221)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(BtnInsrt)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(BtnDeleteP)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(BtnUpdate)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(BtnUpload)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(BtnRst)
                            .addGap(27, 27, 27)
                            .addComponent(BtnCetak, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(btndwnld, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(25, 25, 25))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btndwnld)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnInsrt)
                    .addComponent(BtnDeleteP)
                    .addComponent(BtnUpdate)
                    .addComponent(BtnUpload)
                    .addComponent(BtnCetak)
                    .addComponent(BtnRst))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Penerbit", jPanel2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 543, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(100, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnInsrtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnInsrtActionPerformed
        // TODO add your handling code here:
        InsertDlg dlg = new InsertDlg(this, true, this); // <== ini penting
        dlg.setVisible(true);

        // kalau dialog berhasil menyimpan data, reload tabel
        if (dlg.isSaved()) {
            showTablePenerbit();
        }
    }//GEN-LAST:event_BtnInsrtActionPerformed

    private void BtnDeletePActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDeletePActionPerformed
        // TODO add your handling code here:
        int row = DtPenerbit.getSelectedRow();
        if (row >= 0) {
            // Ambil data dari tabel
            int idp = Integer.parseInt(DtPenerbit.getValueAt(row, 0).toString());
            String nmp = DtPenerbit.getValueAt(row, 1).toString();
            String Alamat = DtPenerbit.getValueAt(row, 2).toString();

            // Panggil dialog, kirim form ini sebagai parent
            DeleteDlgP dialog = new DeleteDlgP(this, true, this, idp, nmp, Alamat);
            dialog.setLocationRelativeTo(this);
            dialog.setVisible(true);

            // Kalau user benar-benar delete, refresh tabel
            if (dialog.isDeleted()) {
                showTablePenerbit();
                showTableBuku();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Pilih data dulu dari tabel!");
        }

    }//GEN-LAST:event_BtnDeletePActionPerformed

    private void BtnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnUpdateActionPerformed
        // TODO add your handling code here:
        int row = DtPenerbit.getSelectedRow();
        if (row != -1) {
            // ambil data dari tabel
            int idp = Integer.parseInt(DtPenerbit.getValueAt(row, 0).toString());
            String nmp = DtPenerbit.getValueAt(row, 1).toString();
            String alamat = DtPenerbit.getValueAt(row, 2).toString();
            // buka dialog update
            UpdateDlgP dialog = new UpdateDlgP(this, true, this, idp, nmp, alamat);
            dialog.setVisible(true);

            // reload tabel setelah update
            if (dialog.isUpdated()) {
                showTablePenerbit();
                showTableBuku();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Pilih data yang mau diupdate dulu!");
        }

        // TODO add your handling code here:

    }//GEN-LAST:event_BtnUpdateActionPerformed

    private void BttnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BttnDeleteActionPerformed
        // TODO add your handling code here:

        // Ambil data dari tabel
        int row = DtBuku.getSelectedRow();
        if (row >= 0) {
            int idb = Integer.parseInt(DtBuku.getValueAt(row, 0).toString());
            String jb = DtBuku.getValueAt(row, 1).toString();
            String tt = DtBuku.getValueAt(row, 2).toString();
            int idp = Integer.parseInt(DtBuku.getValueAt(row, 3).toString());

            DeleteDlgB dialog = new DeleteDlgB(this, true, this, idb, jb, tt, idp);
            dialog.setVisible(true); // 🔹 WAJIB biar dialog muncul!

            // Kalau user benar-benar delete, refresh tabel
            if (dialog.isDeleted()) {
                showTableBuku();
                showTablePenerbit();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Pilih data dulu dari tabel!");
        }
    }//GEN-LAST:event_BttnDeleteActionPerformed

    private void BtnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnInsertActionPerformed
        // TODO add your handling code here:
        InsertDlgB dlg = new InsertDlgB(this, true, this); // <== ini penting
        dlg.setVisible(true);

        // kalau dialog berhasil menyimpan data, reload tabel
        if (dlg.isSaved()) {
            showTableBuku();
        }
    }//GEN-LAST:event_BtnInsertActionPerformed

    private void BttnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BttnUpdateActionPerformed
        // TODO add your handling code here:
        int row = DtBuku.getSelectedRow();
        if (row != -1) {
            // ambil data dari tabel
            int idb = Integer.parseInt(DtBuku.getValueAt(row, 0).toString());
            String jb = DtBuku.getValueAt(row, 1).toString();
            int tt = Integer.parseInt(DtBuku.getValueAt(row, 2).toString());
            int idp = Integer.parseInt(DtBuku.getValueAt(row, 3).toString());

            // buka dialog update
            UpdateDlgB dialog = new UpdateDlgB(this, true, this, idb, jb, tt, idp);
            dialog.setVisible(true);

            // reload tabel setelah update
            if (dialog.isUpdated()) {
                showTableBuku();
                showTablePenerbit();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Pilih data yang mau diupdate dulu!");
        }
    }//GEN-LAST:event_BttnUpdateActionPerformed

    private void BttnUploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BttnUploadActionPerformed
        // TODO add your handling code here:
        JFileChooser jfc = new JFileChooser(FileSystemView.getFileSystemView().getHomeDirectory());
        int returnValue = jfc.showOpenDialog(this);

        if (returnValue != JFileChooser.APPROVE_OPTION) {
            return;
        }

        File filePilihan = jfc.getSelectedFile();
        EntityManagerFactory emf = null;
        EntityManager em = null;

        try (BufferedReader br = new BufferedReader(new FileReader(filePilihan))) {
            String pemisah = "\\s*;\\s*"; // split yang toleran terhadap spasi sekitar ';'

            // BACA HEADER TERLEBIH DAHULU (jika file kosong, hentikan)
            String header = br.readLine();
            if (header == null) {
                JOptionPane.showMessageDialog(this, "File kosong.");
                return;
            }

            // buat factory & entity manager setelah memastikan file bisa dibaca
            emf = Persistence.createEntityManagerFactory("PertemuanKeduabelasPU");
            em = emf.createEntityManager();

            em.getTransaction().begin();
            String baris;
            int lineNo = 1; // header sudah terlewati

            while ((baris = br.readLine()) != null) {
                lineNo++;

                if (baris.trim().isEmpty()) {
                    continue;
                }

                // split tolerant: menghapus spasi di sekitar delimiter
                String[] data = baris.trim().split(pemisah);

                // cek minimal kolom (idb, judul, tahun, idp)
                if (data.length < 4) {
                    // bisa lewati atau tampil pesan; di sini kita lewati baris tidak valid
                    System.err.println("Baris " + lineNo + " di-skip: kolom tidak lengkap -> " + baris);
                    continue;
                }

                String idbStr = data[0].trim();
                String jb = data[1].trim();
                String ttStr = data[2].trim();
                String idpStr = data[3].trim();

                if (idbStr.isEmpty() || jb.isEmpty() || ttStr.isEmpty() || idpStr.isEmpty()) {
                    System.err.println("Baris " + lineNo + " di-skip: ada nilai kosong -> " + baris);
                    continue;
                }

                int idb, tt, idp;
                try {
                    idb = Integer.parseInt(idbStr);
                    tt = Integer.parseInt(ttStr);
                    idp = Integer.parseInt(idpStr);
                } catch (NumberFormatException nfe) {
                    System.err.println("Baris " + lineNo + " di-skip: format angka salah -> " + baris);
                    continue;
                }

                // cek penerbit ada
                Penerbit p = em.find(Penerbit.class, idp);
                if (p == null) {
                    System.err.println("Baris " + lineNo + " di-skip: penerbit tidak ditemukan -> ID " + idp);
                    continue;
                }

                // buat entity Buku dan persist
                Buku b = new Buku();
                b.setIdBuku(idb);
                b.setJudul(jb);
                b.setTahunTerbit(tt);
                b.setIdPenerbit(p);
                em.persist(b);
            }

            em.getTransaction().commit();
            JOptionPane.showMessageDialog(this, "Upload selesai dan berhasil!");
            showTableBuku();

        } catch (IOException ioEx) {
            if (em != null && em.getTransaction().isActive()) {
                em.getTransaction().rollback();
            }
            JOptionPane.showMessageDialog(this, "Gagal membaca file: " + ioEx.getMessage());
        } catch (PersistenceException pex) {
            if (em != null && em.getTransaction().isActive()) {
                em.getTransaction().rollback();
            }
            JOptionPane.showMessageDialog(this, "Id Buku tidak boleh duplicat");
        } catch (Exception ex) {
            if (em != null && em.getTransaction().isActive()) {
                em.getTransaction().rollback();
            }
            JOptionPane.showMessageDialog(this, "Kesalahan saat upload: " + ex.getMessage());
        } finally {
            if (em != null && em.isOpen()) {
                em.close();
            }
            if (emf != null && emf.isOpen()) {
                emf.close();
            }
        }

    }//GEN-LAST:event_BttnUploadActionPerformed

    private void BtnUploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnUploadActionPerformed
        // TODO add your handling code here:
        JFileChooser jfc = new JFileChooser(FileSystemView.getFileSystemView().getHomeDirectory());
        int returnValue = jfc.showOpenDialog(this);

        if (returnValue != JFileChooser.APPROVE_OPTION) {
            return;
        }

        File filePilihan = jfc.getSelectedFile();
        EntityManagerFactory emf = null;
        EntityManager em = null;

        try (BufferedReader br = new BufferedReader(new FileReader(filePilihan))) {
            String pemisah = "\\s*;\\s*"; // split yang toleran terhadap spasi sekitar ';'

            // BACA HEADER TERLEBIH DAHULU (jika file kosong, hentikan)
            String header = br.readLine();
            if (header == null) {
                JOptionPane.showMessageDialog(this, "File kosong.");
                return;
            }

            // buat factory & entity manager setelah memastikan file bisa dibaca
            emf = Persistence.createEntityManagerFactory("PertemuanKeduabelasPU");
            em = emf.createEntityManager();

            em.getTransaction().begin();
            String baris;
            int lineNo = 1; // header sudah terlewati

            while ((baris = br.readLine()) != null) {
                lineNo++;

                if (baris.trim().isEmpty()) {
                    continue;
                }

                // split tolerant: menghapus spasi di sekitar delimiter
                String[] data = baris.trim().split(pemisah);

                // cek minimal kolom (idb, judul, tahun, idp)
                if (data.length < 3) {
                    // bisa lewati atau tampil pesan; di sini kita lewati baris tidak valid
                    System.err.println("Baris " + lineNo + " di-skip: kolom tidak lengkap -> " + baris);
                    continue;
                }

                String idpStr = data[0].trim();
                String nmp = data[1].trim();
                String alamat = data[2].trim();

                if (idpStr.isEmpty() || nmp.isEmpty() || alamat.isEmpty()) {
                    System.err.println("Baris " + lineNo + " di-skip: ada nilai kosong -> " + baris);
                    continue;
                }

                int idp;
                try {
                    idp = Integer.parseInt(idpStr);
                } catch (NumberFormatException nfe) {
                    System.err.println("Baris " + lineNo + " di-skip: format angka salah -> " + baris);
                    continue;
                }

                // buat entity Buku dan persist
                Penerbit p = new Penerbit();
                p.setIdPenerbit(idp);
                p.setNamaPenerbit(nmp);
                p.setAlamat(alamat);
                em.persist(p);
            }

            em.getTransaction().commit();
            JOptionPane.showMessageDialog(this, "Upload selesai dan berhasil!");
            showTablePenerbit();

        } catch (IOException ioEx) {
            if (em != null && em.getTransaction().isActive()) {
                em.getTransaction().rollback();
            }
            JOptionPane.showMessageDialog(this, "Gagal membaca file: " + ioEx.getMessage());
        } catch (PersistenceException pex) {
            if (em != null && em.getTransaction().isActive()) {
                em.getTransaction().rollback();
            }
            JOptionPane.showMessageDialog(this, "Id Penerbit tidak boleh duplicat ");
        } catch (Exception ex) {
            if (em != null && em.getTransaction().isActive()) {
                em.getTransaction().rollback();
            }
            JOptionPane.showMessageDialog(this, "Kesalahan saat upload: " + ex.getMessage());
        } finally {
            if (em != null && em.isOpen()) {
                em.close();
            }
            if (emf != null && emf.isOpen()) {
                emf.close();
            }
        }
    }//GEN-LAST:event_BtnUploadActionPerformed

    private void BttnCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BttnCetakActionPerformed
        JasperReport reports;
        String path = ".\\src\\pertemuankeduabelas\\Buku.jasper";
        try {
            try {
                Class.forName(driver);
                conn = DriverManager.getConnection(koneksi, user, password);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Buku.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(Buku.class.getName()).log(Level.SEVERE, null, ex);
            }

            // Ambil nama user yg login
            String namaLogin = UserNow.getNamaUser();

            // Kirim sebagai parameter ke jasper
            Map<String, Object> params = new HashMap<>();
            params.put("namaUser", namaLogin);

            reports = (JasperReport) JRLoader.loadObjectFromFile(path);

            // Gunakan params
            JasperPrint jprint = JasperFillManager.fillReport(path, params, conn);

            JasperViewer jviewer = new JasperViewer(jprint, false);
            jviewer.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            jviewer.setVisible(true);

        } catch (JRException ex) {
            Logger.getLogger(Buku.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BttnCetakActionPerformed

    private void BtnCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCetakActionPerformed
        // TODO add your handling code here:
        JasperReport reports;

        String path = ".\\src\\pertemuankeduabelas\\Penerbit.jasper";
        try {
            try {
                Class.forName(driver);
                conn = DriverManager.getConnection(koneksi, user, password);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Penerbit.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(Penerbit.class.getName()).log(Level.SEVERE, null, ex);
            }
             String namaLogin = UserNow.getNamaUser();

            // Kirim sebagai parameter ke jasper
            Map<String, Object> params = new HashMap<>();
            params.put("namaUser", namaLogin);

            reports = (JasperReport) JRLoader.loadObjectFromFile(path);

            // Gunakan params
            JasperPrint jprint = JasperFillManager.fillReport(path, params, conn);
            JasperViewer jviewer = new JasperViewer(jprint, false);
            jviewer.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            jviewer.setVisible(true);
        } catch (JRException ex) {
            Logger.getLogger(Penerbit.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BtnCetakActionPerformed

    private void BtnresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnresetActionPerformed
        // TODO add your handling code here:
        EntityManager em = Persistence.createEntityManagerFactory("PertemuanKeduabelasPU").createEntityManager();

        em.getTransaction().begin();
        em.createNativeQuery("TRUNCATE TABLE buku RESTART IDENTITY CASCADE").executeUpdate();
        em.getTransaction().commit();
        showTableBuku();
        em.close();

    }//GEN-LAST:event_BtnresetActionPerformed

    private void BtnRstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRstActionPerformed
        // TODO add your handling code here:
        EntityManager em = Persistence.createEntityManagerFactory("PertemuanKeduabelasPU").createEntityManager();

        em.getTransaction().begin();
        em.createNativeQuery("TRUNCATE TABLE penerbit RESTART IDENTITY CASCADE").executeUpdate();
        em.getTransaction().commit();
        showTablePenerbit();
        em.close();
    }//GEN-LAST:event_BtnRstActionPerformed

    private void BtndownloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtndownloadActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Simpan sebagai CSV");
// Default nama file
        fileChooser.setSelectedFile(new java.io.File("Data_Buku.csv"));
        int userSelection = fileChooser.showSaveDialog(this);
        if (userSelection == JFileChooser.APPROVE_OPTION) {
            File fileToSave = fileChooser.getSelectedFile();
            try (FileWriter fw = new FileWriter(fileToSave)) {
                DefaultTableModel model = (DefaultTableModel) DtBuku.getModel();
                int colCount = model.getColumnCount();
                int rowCount = model.getRowCount();
                // Tulis nama kolom
                for (int i = 0; i < colCount; i++) {
                    fw.write(model.getColumnName(i));
                    if (i < colCount - 1) {
                        fw.write(";");
                    }
                }
                fw.write("\n");
                // Tulis data baris
                for (int r = 0; r < rowCount; r++) {
                    for (int c = 0; c < colCount; c++) {
                        Object value = model.getValueAt(r, c);
                        String cell = (value == null) ? "" : value.toString().replace(";", ",");
                        fw.write(cell);
                        if (c < colCount - 1) {
                            fw.write(";");
                        }
                    }
                    fw.write("\n");
                }
                JOptionPane.showMessageDialog(null,
                        "File berhasil disimpan:\n" + fileToSave.getAbsolutePath());
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null,
                        "Gagal menyimpan file: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_BtndownloadActionPerformed

    private void btndwnldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndwnldActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Simpan sebagai CSV");

// Default nama file
        fileChooser.setSelectedFile(new java.io.File("Penerbit_Buku.csv"));

        int userSelection = fileChooser.showSaveDialog(this);

        if (userSelection == JFileChooser.APPROVE_OPTION) {

            File fileToSave = fileChooser.getSelectedFile();

            try (FileWriter fw = new FileWriter(fileToSave)) {

                DefaultTableModel model = (DefaultTableModel) DtPenerbit.getModel();
                int colCount = model.getColumnCount();
                int rowCount = model.getRowCount();

                // Tulis nama kolom
                for (int i = 0; i < colCount; i++) {
                    fw.write(model.getColumnName(i));
                    if (i < colCount - 1) {
                        fw.write(";");
                    }
                }
                fw.write("\n");

                // Tulis data baris
                for (int r = 0; r < rowCount; r++) {
                    for (int c = 0; c < colCount; c++) {
                        Object value = model.getValueAt(r, c);

                        String cell = (value == null) ? "" : value.toString().replace(";", ",");

                        fw.write(cell);

                        if (c < colCount - 1) {
                            fw.write(";");
                        }
                    }
                    fw.write("\n");
                }

                JOptionPane.showMessageDialog(null,
                        "File berhasil disimpan:\n" + fileToSave.getAbsolutePath());

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null,
                        "Gagal menyimpan file: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_btndwnldActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new MenuUtama().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCetak;
    private javax.swing.JButton BtnDeleteP;
    private javax.swing.JButton BtnInsert;
    private javax.swing.JButton BtnInsrt;
    private javax.swing.JButton BtnRst;
    private javax.swing.JButton BtnUpdate;
    private javax.swing.JButton BtnUpload;
    private javax.swing.JButton Btndownload;
    private javax.swing.JButton Btnreset;
    private javax.swing.JButton BttnCetak;
    private javax.swing.JButton BttnDelete;
    private javax.swing.JButton BttnUpdate;
    private javax.swing.JButton BttnUpload;
    private javax.swing.JTable DtBuku;
    private javax.swing.JTable DtPenerbit;
    private javax.swing.JButton btndwnld;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane2;
    // End of variables declaration//GEN-END:variables
}
